name: Quiz Generator

on:
  push:
    paths:
      - 'Quiz.csv'
  pull_request:
    paths:
      - 'Quiz.csv'

jobs:
  generate-quiz:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run quiz generator
      run: python generate_quiz.py
      
    - name: Commit generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --staged --quiet || git commit -m "Auto-generate quiz files from Quiz.csv"
        git push
